
%  Input: xa,xb= extrema of computational domain Omega=(xa,xb)
%         ne = number of elements
%         npdx = number of nodes in each element (the same in every element)
%         nov = local -global map, previously generated by cosnov1d
%         x = LGL nodes in [-1,1], previously generated by xwlgl
%         wx = LGL weigths in [-1,1], previously generated by xwlgl
%
%
% Output: xx = 2-indexes array of size (2,ne): xx(1:2,ie)=[xa_ie;xb_ie]
%         jacx = array (length(jacx)=ne); jacx(ie)= jacobian of 
%                of the map F_ie:[-1,1]---->[xa_ie,xb_ie]
%         xy = column array with global mesh, length: noe=nov(npdx,ne)
%         ww = column array with global weigths, length: noe=nov(npdx,ne)
%              diag(ww) is the mass matrix associated to SEM discretization

clear all;
close all;
clc;
xa = 0;
xb = 1;
ne = 80; 
h =num2str(1/ne, '%.4f');
npdx = 2; %the number of nodes per element along a dimension has to be 2 (the two vertices)
% to get nodes_coordinates file that account only for the coordinates of
% the vertices, and not for all the nodes of the mesh (the internal ones too)
nov=cosnov_1d(npdx,ne);
[x,wx]=xwlgl(npdx);



[xx,jacx,xy,ww]=mesh_1d(xa,xb,ne,npdx,nov,x,wx);


%once the matrixes are correclty constructed, we move onto the creation of the
%csv files

%write nodes_coordinates.csv (global mesh nodes and corresponding coordinates)



noe=nov(npdx,ne);

numbers = [noe, ne];
T = array2table(numbers);
T.Properties.VariableNames(1:2) = {'Number of total nodes','Number of total elements'};
writetable(T,strcat(strcat('../meshes/1D_meshes/numbers_',h),'.csv'));



nodes = zeros(noe, 2);
nodes(1:noe, 1) = (1:noe);
nodes (:,2) = xy;

T = array2table(nodes);
T.Properties.VariableNames(1:2) = {'node_id','node_coordinate_'};
writetable(T,strcat(strcat('../meshes/1D_meshes/nodes_coordinates_',h),'.csv'));




%write elements_vertexes.csv (each vertex inside each element)
%for this purpose the original mesh_1d function as been sligthly modified

elems = zeros(ne, 3);
elems(:,1) = (1:ne);
elems(:, 2:3) = nov';

T = array2table(elems);
T.Properties.VariableNames(1:3) = {'ElementID','GlobalId_1', 'GlobalId_2'};
writetable(T,strcat(strcat('../meshes/1D_meshes/elements_vertexes_',h),'.csv'));




